// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDrz7vgcB-Sz93MxXGjvw23NDkb8sjrnH4',
    appId: '1:27302920624:web:e5aba7103b36561bc5d675',
    messagingSenderId: '27302920624',
    projectId: 'lifestyle-a1f09',
    authDomain: 'lifestyle-a1f09.firebaseapp.com',
    storageBucket: 'lifestyle-a1f09.appspot.com',
    measurementId: 'G-10YB7292XC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyARfhF02A-VMrYvbJSw9ugeWtQ85jY9Y4A',
    appId: '1:27302920624:android:c7234335c59f2d09c5d675',
    messagingSenderId: '27302920624',
    projectId: 'lifestyle-a1f09',
    storageBucket: 'lifestyle-a1f09.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCVWxhWK22Or3lQ54-IeBm-Al75FyZD3z8',
    appId: '1:27302920624:ios:e37cabcde9a2ea24c5d675',
    messagingSenderId: '27302920624',
    projectId: 'lifestyle-a1f09',
    storageBucket: 'lifestyle-a1f09.appspot.com',
    iosClientId: '27302920624-rkhepqijm845vll0btufc9g3uingucru.apps.googleusercontent.com',
    iosBundleId: 'com.example.lifestyle',
  );
}
